config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations',  sessions: 'users/sessions', passwords: 'users/passwords' }

  scope 'account' do
    get 'wall', to: 'account#wall', as: 'account_wall'

    # Questions from logged-in user perspective

    get 'questions/:id/answer', to: 'account#answer', as: 'account_answer'
    patch 'questions/:id/answer', to: 'account#do_answer', as: 'do_account_answer'
    get 'questions/:id', to: 'account#question', as: 'account_question'
    delete 'questions/:id', to: 'account#delete_question', as: 'account_delete_question'
    delete 'questions/:id/answer', to: 'account#delete_answer', as: 'account_delete_answer'

    post 'questions/random', to: 'account#random_question', as: 'account_random_question'

    get 'questions', to: 'account#questions', as: 'account_questions'
    delete 'questions', to: 'account#delete_questions', as: 'account_delete_questions'

    # Like and unlike question
    post 'questions/:id/like', to: 'likes#like', as: 'like_question'

    get 'follows', to: 'account#follows', as: 'account_follow'
    get 'search', to: 'account#search', as: 'account_search'
    post 'search', to: 'account#do_search', as: 'account_do_search'

    scope 'notifications' do
      get 'perks', to: 'notifications#perks', as: 'account_notifications_perks'
      get 'answers', to: 'notifications#answers', as: 'account_notifications_answers'
    end

    scope 'settings' do
      get 'profile', to: 'settings#profile', as: 'account_settings'
      patch 'profile', to: 'settings#update_profile', as: 'account_settings_update'
      # Avatar
      get 'avatar', to: 'settings#avatar', as: 'account_settings_avatar'
      patch 'avatar', to: 'settings#update_avatar', as: 'account_settings_avatar_update'

    end
  end

  # Users profile
  get ':username/answer/:id', to: 'profile#answer', as: 'profile_answer'
  get ':username/gifts', to: 'profile#gifts', as: 'profile_gifts'
  get ':username/best', to: 'profile#best', as: 'profile_best'
  post ':username/follow', to: 'profile#follow', as: 'profile_follow'
  post ':username/unfollow', to: 'profile#unfollow', as: 'profile_unfollow'
  post ':username/ask', to: 'profile#ask', as: 'profile_ask'
  get ':username', to: 'profile#answers', as: 'profile_answers'

  root 'home#home'
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  belongs_to :question, :dependent => :destroy
  belongs_to :user, :dependent => :destroy

  def self.like(user, question)
    n = Notification.new
    n.user_id = question.to
    n.who_id = user
    n.question_id = question.id
    n.kind = 1
    n.seen = false
    n.created_at = Time.now
    n.save
  end

  def self.reply(question)
    if question.from.nil?
      return
    end

    n = Notification.new
    n.user_id = question.from
    n.who_id = question.to
    n.question_id = question.id
    n.kind = 2
    n.seen = false
    n.created_at = Time.now
    n.save
  end

  def self.likes(user)
    set_seen(user, 1)
    likes = get_notifications(user, 1)
    return likes
  end

  def self.replies(user)
    set_seen(user, 2)
    replies = get_notifications(user, 2)
    return replies
  end

  def self.unseen_likes(user)
    get_unseen_notifications(user, 1)
  end

  def self.unseen_replies(user)
    get_unseen_notifications(user, 2)
  end

  def self.set_seen(user, kind)
    where(user_id: user, kind: kind).update_all(seen: true)
  end

  protected
  def self.get_notifications(user, kind)
    where(user_id: user).where(kind: kind)
  end

  def self.get_unseen_notifications(user, kind)
    where(user_id: user).where(kind: kind).where(seen: false)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def perks
    @notifications = Notification.likes current_user.id
  end

  def answers
    @notifications = Notification.replies current_user.id
  end
end

app/views/notifications/answers.html.erb
<div class="container main-content wall">
  <div class="row answers">
    <div class="col-md-12" role="tabpanel">
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="answers">
          <ul class="list-unstyled">
            <% @notifications.each do |notification| %>
                <li>
                  <%= render 'shared/delete_question', {answer: notification.question} %>
                  <img src="<%= notification.question.receiver.avatar.url %>" class="friend-avatar pull-left" alt="friend picture">

                  <%= render 'shared/question', {answer: notification.question} %>

                  <div class="meta clearfix">
                    <span class="text-muted"><%= time_ago_in_words notification.question.replied_at %> ago</span>
                    <a href="<%= profile_answers_url(notification.question.receiver.username) %>">
                      <%= notification.question.receiver.username %>
                    </a>
                    <%= render 'shared/like', {answer: notification.question} %>
                  </div>
                </li>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/notifications/perks.html.erb
<div class="container main-content">
  <div class="row notifications-list">
    <div class="col-md-12 clearfix">
      <h4><strong>notifications</strong></h4>
      <ul class="list-unstyled">
        <% @notifications.each do |notification| %>
            <li class="clearfix">
              <a href="#" class="go-to">
                <img src="<%= notification.user.avatar_url %>" class="friend-avatar pull-left img60_60" alt="friend avatar">
              </a>
              <div class="meta pull-left">
                <p>
                  <a href="#"><%= notification.user.username %></a>
                  likes your
                  <%= link_to 'answer', profile_answer_path(notification.user.username, notification.question.id) %>
                </p>
                <p class="text-muted">
                  <%= time_ago_in_words notification.question.replied_at %>
                </p>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>