config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations',  sessions: 'users/sessions', passwords: 'users/passwords' }

  scope 'account' do
    get 'wall', to: 'account#wall', as: 'account_wall'

    # Questions from logged-in user perspective

    get 'questions/:id/answer', to: 'account#answer', as: 'account_answer'
    patch 'questions/:id/answer', to: 'account#do_answer', as: 'do_account_answer'
    get 'questions/:id', to: 'account#question', as: 'account_question'
    delete 'questions/:id', to: 'account#delete_question', as: 'account_delete_question'
    delete 'questions/:id/answer', to: 'account#delete_answer', as: 'account_delete_answer'

    post 'questions/random', to: 'account#random_question', as: 'account_random_question'

    get 'questions', to: 'account#questions', as: 'account_questions'
    delete 'questions', to: 'account#delete_questions', as: 'account_delete_questions'

    # Like and unlike question
    post 'questions/:id/like', to: 'likes#like', as: 'like_question'

    get 'follows', to: 'account#follows', as: 'account_follow'
    get 'search', to: 'account#search', as: 'account_search'
    post 'search', to: 'account#do_search', as: 'account_do_search'

    scope 'notifications' do
      get 'perks', to: 'notifications#perks', as: 'account_notifications_perks'
      get 'answers', to: 'notifications#answers', as: 'account_notifications_answers'
    end

    scope 'settings' do
      get 'profile', to: 'settings#profile', as: 'account_settings'
      patch 'profile', to: 'settings#update_profile', as: 'account_settings_update'
      # Avatar
      get 'avatar', to: 'settings#avatar', as: 'account_settings_avatar'
      patch 'avatar', to: 'settings#update_avatar', as: 'account_settings_avatar_update'

    end
  end

  # Users profile
  get ':username/answer/:id', to: 'profile#answer', as: 'profile_answer'
  get ':username/gifts', to: 'profile#gifts', as: 'profile_gifts'
  get ':username/best', to: 'profile#best', as: 'profile_best'
  post ':username/follow', to: 'profile#follow', as: 'profile_follow'
  post ':username/unfollow', to: 'profile#unfollow', as: 'profile_unfollow'
  post ':username/ask', to: 'profile#ask', as: 'profile_ask'
  get ':username', to: 'profile#answers', as: 'profile_answers'

  root 'home#home'
end

app/views/shared/_delete_question.html.erb
<% if current_user and answer.receiver.id == current_user.id %>
    <a rel="nofollow" data-method="delete" href="<%= account_delete_answer_url(answer.id) %>">
      <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </a>
<% end %>

app/views/shared/_empty.html.erb
<div class="col-md-12 no-questions">
  <h4 class="link">ask.me/<%= current_user.username %></h4>
  <p>This is the link to your profile. Share it with your friends to get more questions.</p>
</div>

app/views/shared/_follow.html.erb
<% if current_user.following? user %>
    <button user-id="<%= user.username %>" type="button" style="display: none;" class="btn btn-success pull-right follow u-<%= user.username %>">
      Folow
    </button>
    <button user-id="<%= user.username %>" type="button" class="btn btn-default pull-right unfollow u-<%= user.username %>">
      Unfolow
    </button>
<% else %>
    <button user-id="<%= user.username %>" type="button" class="btn btn-success pull-right follow u-<%= user.username %>">Folow</button>
    <button user-id="<%= user.username %>" type="button" style="display: none;" class="btn btn-default pull-right unfollow u-<%= user.username %>">Unfolow</button>
<% end %>

app/views/shared/_like.html.erb
<% if user_signed_in? and  current_user.id !=answer.receiver.id %>
    <button answer-id="<%= answer.id %>" type="button" class="glyphicon glyphicon-heart btn-like pull-right <%= current_user.voted_for?(answer) ? 'liked' : '' %>">
    </button>
<% end %>

<span class="text-muted pull-right who-likes-<%= answer.id %>">
  <% if answer.cached_votes_up > 0 %>
    <%= pluralize(answer.cached_votes_up, 'person likes', 'persons like') %> this
  <% end %>
</span>

app/views/shared/_navbar_in.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-md-12 clearfix">
        <a class="navbar-brand" href="<%= account_wall_url %>">ask<span>.me</span></a>
        <div class="notifications navbar-left">
          <ul class="list-inline">
            <li>
              <a href="<%= account_notifications_perks_url %>">
              <button class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-heart"></span>
                <% if @likes > 0 %>
                    <span class="badge"><%= @likes %></span>
                <% end %>
              </button>
              </a>
            </li>
            <li>
              <a href="<%= account_questions_url %>">
                  <button class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-question-sign"></span>
                    <% if @unanswered.size > 0 %>
                    <span class="badge"><%= @unanswered.size %></span>
                    <% end %>
                  </button>
              </a>
            </li>
            <li>
              <a href="<%= account_notifications_answers_url %>" >
              <button class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-share-alt"></span>
                <% if @replies > 0 %>
                    <span class="badge"><%= @replies %></span>
                <% end %>
              </button>
              </a>
            </li>
          </ul>
        </div>
        <nav class="navbar-right logged-in-nav">
          <ul class="list-inline">
            <li>
              <%= active_link_to 'Home', account_wall_path %>
            </li>
            <li>
              <%= active_link_to ("Questions <span>(#{@unanswered.size})</span>").html_safe, account_questions_path  %>
            </li>
            <li>
              <%= active_link_to 'Profile', profile_answers_path(current_user.username) %>
            </li>
            <li>
              <%= active_link_to 'Friends', account_follow_path %>
            </li>
            <li>
              <%= active_link_to 'Search', account_search_path %>
            </li>
            <li>
              <%= active_link_to 'Settings', account_settings_path %>
            </li>
            <li>
              <%= link_to ('<span class="glyphicon glyphicon-log-out"></span>').html_safe, destroy_user_session_path, :method => :delete %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div> <!-- end of navbar -->

app/views/shared/_navbar_out.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-md-12 clearfix">
        <a class="navbar-brand" href="<%= root_url %>">ask<span>.me</span></a>
        <div class="pull-right link-login">
          <span>Have an account?</span>
          <a href="<%= new_user_session_url %>">
            <button class="btn btn-default btn-login" id="modal-trigger">Login</button>
          </a>
        </div>
      </div>
    </div>
  </div>
</div> <!-- end of navbar -->

app/views/shared/_profile.html.erb
<div class="row user-information">
  <div class="col-md-2">
    <%= image_tag @user.avatar.url, :class => 'profile-picture' %>
  </div>
  <div class="col-md-6">
    <strong class="profile-username"><%= @user.fullname %></strong>
    <span class="text-muted">| @<%= @user.username %></span>
    <span class="display-block"><%= @user.location %></span>

    <p class="text-muted">
      <em>
        <%= @user.description %>
      </em>
    </p>

  </div>
  <div class="col-md-4">
    <ul class="list-inline text-right trafic-info">
      <li>
        <a href="<%= url_for profile_answers_path %>">
          <strong><%= @answers.count %></strong>
          <span class="display-block">answers</span>
        </a>
      </li>
      <li>
        <a href="<%= profile_best_url %>">
          <strong><%= @user.total_likes %></strong>
          <span class="display-block">likes</span>
        </a>
      </li>
      <% if user_signed_in? and current_user.id == @user.id %>
        <li>
          <strong><%= @user.followers_count %></strong>
          <span class="display-block">followers</span>
        </li>
      <% end %>
    </ul>
    <div class="actions text-right">
      <% if user_signed_in? and current_user.id != @user.id %>
          <% if current_user.following?(@user) %>
              <%= link_to 'Unfollow', profile_unfollow_path, :class => 'btn btn-default', :method => :post %>
          <% else %>
              <%= link_to 'Follow', profile_follow_path, :class => 'btn btn-success', :method => :post %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row post-question">
  <div class="col-md-12">
    <h4>
      <strong><%= @user.title %></strong>
    </h4>
    <%= form_for(Question.new, url: profile_ask_url) do |f| %>
      <div class="panel panel-default">
        <label for="question" class="sr-only">Question:</label>
        <%= f.text_area :question, :class => 'emoji character-limit' %>
        <div class="panel-footer clearfix">
          <span id="remaining" class="pull-left letters-left character-count" data-default-value="300">300</span>
          <div class="pull-right">
            <% if user_signed_in? %>
            <label class="check"><%= f.check_box :anonymous %>Anonymous Question</label>
            <% end %>
            <%= f.submit 'Ask', :class => 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_question.html.erb
<p>
  <strong><%= emojify answer.question %></strong>
  <%= format_question_sender_link answer %>
</p>
<p><%= emojify answer.reply %></p>